### PR TITLE
Kindly do the Merge. Updated !!!

### PR DESCRIPTION
**Pull request by dark-1**
@ErnyTech friend ,

Kindly Take a Look.

Best Regards.

### CODE REVIEW

**Comment by dark-1** [comment]
Going through some Problems will Open Request as soon as I FIX'ed it.

**Comment by dark-1** [comment]
Yep! Critical Bug Fixed. 👍

**Comment by ErnyTech** [comment]
Thanks! Merged

**Comment by dark-1** [comment]
👍

**Pull request merged**
